service: yrtt-tasks-backend-csharp-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless

package:
  individually: true

functions:
  tasks-api:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::GetTasks
    package:
      artifact: bin/Release/netcoreapp3.1/tasks-api.zip
    events:
      - httpApi:
          path: /users/{userId}/tasks
          method: get
